name: brain-games
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: cd ..
      - name: run-linter
        run: npx eslint /src/cli.js
      - run: npx exlint /bin/brain-games.js
