name: brain-games
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }}
      - name: run-linter
        run: npx eslint src/.
      - run: npx exlint bin/.
